# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'vezdecode_emotions' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for vezdecode_emotions
	pod "TinyConstraints"
end
